name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: go install github.com/jstemmer/go-junit-report

    - name: Build
      run: go build -v

    - name: Test
      run: go test -race -v 2>&1 | go-junit-report > report.xml

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: "*.xml"
        reporter: java-junit
