name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: go get github.com/tebeka/go2xunit

    - name: Build
      run: go build -v

    - name: Test
      run: |
        go test -race -v | go2xunit > test_output.xml
        ls -la

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Go Test
        path: 'test_output.xml'
        reporter: dotnet-trx
